### ISSUE TITLE
请大佬帮忙看下项目npm run start报错了

### ISSUE THREAD

**Issue by superchangme** [xieyezi/2019-ncov-vue3-version#2]

**Comment by superchangme** [comment]
![宇信通图片_20200512125426](https://user-images.githubusercontent.com/7008154/81639881-c2380580-944f-11ea-91d5-096cad7cb8b8.png)

**Comment by superchangme** [comment]
yarn serve v0.27.5
(node:59424) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ vue-cli-service serve
 ERROR  Error loading vue.config.js:
 ERROR  Error: Cannot find module 'webpack/lib/ModuleFilenameHelpers'
Error: Cannot find module 'webpack/lib/ModuleFilenameHelpers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\test\2019-ncov-vue3-version\node_modules\_compression-webpack-plugin@3.1.0@compression-webpack-plugin\dist\index.js:20:53)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2019-ncov-vue3-version@0.1.0 start: `yarn serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2019-ncov-vue3-version@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\changjtb.ZZYT\AppData\Roaming\npm-cache\_logs\2020-05-12T04_51_26_014Z-debug.log
终端进程已终止，退出代码: 1

**Comment by xieyezi** [comment]
@superchangme 请问你执行的是什么命令呢？以及你的vue cli是哪个版本呢？

**Comment by superchangme** [comment]
vue cli版本 4.3.1
node版本 10.16.0
npm run serve和run start都试了，报一样的错

**Comment by superchangme** [comment]
> @superchangme 请问你执行的是什么命令呢？以及你的vue cli是哪个版本呢？

vue cli版本 4.3.1
node版本 10.16.0
npm run serve和run start都试了，报一样的错

**Comment by superchangme** [comment]
> > @superchangme 请问你执行的是什么命令呢？以及你的vue cli是哪个版本呢？
> 
> vue cli版本 4.3.1
> node版本 10.16.0
> npm run serve和run start都试了，报一样的错

我手动安装了webpack后可以了，不是说vue集成了webpack吗，还是我的姿势不对，求大佬教诲。

**Comment by superchangme** [comment]
又报个新错：
> 2019-ncov-vue3-version@0.1.0 start d:\test\2019-ncov-vue3-version
> yarn serve

yarn serve v0.27.5
(node:68584) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ vue-cli-service serve
 INFO  Starting development server...
 ERROR  Error: Cannot find module 'ts-loader/package.json'
Error: Cannot find module 'ts-loader/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at api.chainWebpack.config (D:\test\2019-ncov-vue3-version\node_modules\_@vue_cli-plugin-typescript@4.2.3@@vue\cli-plugin-typescript\index.js:34:22)
    at webpackChainFns.forEach.fn (d:\test\2019-ncov-vue3-version\node_modules\_@vue_cli-service@4.2.3@@vue\cli-service\lib\Service.js:236:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (d:\test\2019-ncov-vue3-version\node_modules\_@vue_cli-service@4.2.3@@vue\cli-service\lib\Service.js:236:26)
    at Service.resolveWebpackConfig (d:\test\2019-ncov-vue3-version\node_modules\_@vue_cli-service@4.2.3@@vue\cli-service\lib\Service.js:240:48)
    at PluginAPI.resolveWebpackConfig (d:\test\2019-ncov-vue3-version\node_modules\_@vue_cli-service@4.2.3@@vue\cli-service\lib\PluginAPI.js:132:25)
    at serve (d:\test\2019-ncov-vue3-version\node_modules\_@vue_cli-service@4.2.3@@vue\cli-service\lib\commands\serve.js:74:31)
    at Service.run (d:\test\2019-ncov-vue3-version\node_modules\_@vue_cli-service@4.2.3@@vue\cli-service\lib\Service.js:230:12)
    at Object.<anonymous> (d:\test\2019-ncov-vue3-version\node_modules\_@vue_cli-service@4.2.3@@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
error Command failed with exit code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2019-ncov-vue3-version@0.1.0 start: `yarn serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2019-ncov-vue3-version@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by superchangme** [comment]
大佬，结贴吧，我的yarn有问题，有一个0.2的版本一直删不掉，最后发现是在c盘program file下删除后，装了最新的yarn之后，世界和平了。
